<?php


/**
 * Implements hook_menu
 */
function salesforce_webform_menu()
{
	$items['node/%/submission/%/resendsalesforce'] = array(
		'title' => 'Resend to Salesforce',
		'description' => 'Resend Webform Submission to Salesforce',
		'page callback' => 'salesforce_webform_resend_salesforce',
		'page arguments' => array(1, 3),
		'access arguments' => array('access administration pages'),
		'type' => MENU_CALLBACK
	);
	
	return $items;
} // end function salesforce_webform_menu


/**
 * Implementation of hook_node_load
 * 
 * This function is called every time a node is loaded from the database.
 * 
 * Essentially looking to ensure we are looking at a specific node, if true
 * then checking to see if the node is of type webform or not. If true, then
 * check to see if license key generation is suppose to occur, if true, then
 * set generate_license on $node object to true.
 */
function salesforce_webform_node_load($nodes, $types)
{
	// We only care if we are loading a single node.
	if (count($nodes) > 1)
	{
		return;
	}

	$node = $nodes[key($nodes)];

  // Check if node can have a form
  if (in_array($node->type, webform_variable_get('webform_node_types'))) {
		$result = db_select('salesforce_webforms', 'sw')
					->fields('sw')
					->condition('nid', $node->nid)
					->execute()
					->fetchObject();

		if (!empty($result))
		{
			$node->use_salesforce    = $result->enabled;
			$node->salesforce_object = $result->object;
			$node->salesforce_campaign = $result->campaign;
			$node->salesforce_campaign_status = $result->campaign_status;
			$node->salesforce_object_upsert = $result->object_upsert;
		}
		else
		{
			$node->use_salesforce = 0;
		}		
	}
} // end function salesforce_webform_node_load


/**
 * Implementation of hook_licensing_node_insert
 * 
 * When a node is updated this gets called and in turn calls the private
 * function _salesforce_webform_node_insert_update for action.
 */
function salesforce_webform_node_insert($node)
{
	_salesforce_webform_node_insert_update($node);
} // end function salesforce_webform_node_insert


/**
 * Implementation of hook_licensing_node_update
 * 
 * When a node is updated this gets called and in turn calls the private
 * function _salesforce_webform_node_insert_update for action.
 */
function salesforce_webform_node_update($node)
{
	_salesforce_webform_node_insert_update($node);
} // end function salesforce_webform_node_update


/**
 * Private Function (only to be used from within this module)
 * 
 * This function is called by either the hook_node_update or hook_node_insert callbacks,
 * its purpose is to validate if license key generation is suppose to happen and if so then
 * set the generate_license value on the $node object true.
 */
function _salesforce_webform_node_insert_update($node)
{
//	if ($node->type != 'webform' && !isset($node->salesforce_webform_settings['use_salesforce']))
	if (!isset($node->salesforce_webform_settings['use_salesforce']))
		return;

	$result = db_select('salesforce_webforms', 'sw')
				->fields('sw')
				->condition('nid', $node->nid)
				->execute()
				->fetchObject();

	if (empty($result))
	{
		db_insert('salesforce_webforms')
			->fields(array(
				'nid' => $node->nid,
				'enabled' => ($node->salesforce_webform_settings['use_salesforce'] == 1) ? 1 : 0,
				'object' => $node->salesforce_webform_settings['salesforce_object'],
				'object_upsert' => $node->salesforce_webform_settings['salesforce_object_upsert'],
				'campaign' => $node->salesforce_webform_settings['salesforce_campaign'],
				'campaign_status' => $node->salesforce_webform_settings['salesforce_campaign_status'],
			))
			->execute();
	}
	else
	{

		db_update('salesforce_webforms')
			->fields(array(
				'enabled' => ($node->salesforce_webform_settings['use_salesforce'] == 1) ? 1 : 0,
				'object' => $node->salesforce_webform_settings['salesforce_object'],
				'object_upsert' => $node->salesforce_webform_settings['salesforce_object_upsert'],
				'campaign' => $node->salesforce_webform_settings['salesforce_campaign'],
				'campaign_status' => $node->salesforce_webform_settings['salesforce_campaign_status'],
			))
			->condition('nid', $node->nid)
			->execute();
	}

} // end function _salesforce_webform_node_insert_update

/**
 * Private Function (only to be used from within this module)
 * 
 * This function is called by the hook_form_alter callbacks to provide 
 * the campaigns available in Salesforce.
 */
function _salesforce_webform_get_campaigns() {
  $options = array();
  $records = salesforce_api_query("SELECT Id, Name from Campaign");
  foreach ($records as $record) {
    $sObject = new SObject($record);
    $options[$sObject->Id] = $sObject->Name;
  }
  return $options;
}

/**
 * Private Function (only to be used from within this module)
 * 
 * This function is called by the hook_form_alter callbacks to provide 
 * the campaign statuses available in Salesforce.
 */
function _salesforce_webform_get_campaign_status() {
  $options = array();
  $records = salesforce_api_query("SELECT Label from CampaignMemberStatus");
  foreach ($records as $record) {
    $sObject = new SObject($record);
    $options[$sObject->Label] = $sObject->Label;
  }
  return $options;
}


/**
 * Implementation of hook_form_alter
 * 
 * Alter the webform_node_form with Salesforce settings in the additional
 * settings section. Allows the ability to send to Salesforce and to define
 * which Salesforce object the webform submissions will be mapped to.
 */
function salesforce_webform_form_alter(&$form, &$form_state, $form_id)
{
  // Show warnings
  if ($form_id == "webform_components_form" && $form["#node"]->use_salesforce == 1) {
      $result = db_select('salesforce_webform_fieldmaps', 'swf')
					->fields('swf', array('cid'))
					->condition('nid', $form['#node']->webform['components'][1]['nid'])
					->condition('sffname', $upsertfield = $form['#node']->salesforce_object_upsert)
					->execute()
					->fetchObject();
					
			if(!isset($result->cid)) drupal_set_message(t("Please create a form field of Salesforce field type %upsert in order to enable deduplication on %upsert. ",array("%upsert"=>$form['#node']->salesforce_object_upsert)), "error");
			
			if (isset($result->cid) && !$form['#node']->webform['components'][$result->cid]['mandatory']) drupal_set_message(t("Webform component %component should be mandatory in order to ensure deduplication on %upsert. ",array("%component"=>$form['#node']->webform['components'][$result->cid]['name'],"%upsert"=>$form['#node']->salesforce_object_upsert)), "error");
  }
  
  // Check if node has a form
  if (in_array(substr($form_id,0,-10), webform_variable_get('webform_node_types'))) {
		$types = array();
		foreach (salesforce_api_describeGlobal()->types as $type)
		{
			$types[$type->name] = $type->label;
		}
		$campaigns = array_merge(array('none' => '--None--'),_salesforce_webform_get_campaigns());
		$statuses = array_merge(array('auto' => '--Auto--'),_salesforce_webform_get_campaign_status());
     $selected = isset($form_state['values']['salesforce_webform_settings']['salesforce_object']) ? $form_state['values']['salesforce_webform_settings']['salesforce_object'] : "Contact";
     
     if(isset($form['#node']->salesforce_object) && $form['#node']->salesforce_object != "") $selected = $form['#node']->salesforce_object;
    
		/* Start SalesForce Settings Form */
		$form['salesforce_webform_settings'] = array(
			'#type' => 'fieldset',
			'#title' => t('SalesForce Settings'),
			'#collapsible' => TRUE,
		    '#collapsed' => FALSE,
			'#tree' => TRUE,
			'#group' => 'additional_settings',
			'#attributes' => array(
		      'class' => array('salesforce-webform-settings-form'),
		    ),
		    '#attached' => array(
		      'js' => array(drupal_get_path('module', 'salesforce_webform') . '/salesforce_webform.js'),
		    ),
			'#weight' => 10
		);
		$form['salesforce_webform_settings']['use_salesforce'] = array (
			'#type' => 'checkbox',
			'#title' => t('Submit to SalesForce'),
			'#default_value' => (isset($form['#node']->use_salesforce) && $form['#node']->use_salesforce == 1) ? 1 : 0,
			'#description' => t('If yes, the form will be sent via SOAP to SalesForce.  Make sure you have specified the username & password in Administer->Site Configuration->SalesForce Webform first.')
		);
		$form['salesforce_webform_settings']['salesforce_object'] = array(
			'#type' => 'select',
			'#title' => t('Object Type'),
			'#options' => $types,
			'#description' => t('Select which object type to submit to.'),
			'#default_value' => (isset($form['#node']->salesforce_object)) ? $form['#node']->salesforce_object : 'Contact',
			'#ajax' => array(
        // When 'event' occurs, Drupal will perform an ajax request in the
        // background. Usually the default value is sufficient (eg. change for
        // select elements), but valid values include any jQuery event,
        // most notably 'mousedown', 'blur', and 'submit'.
        // 'event' => 'change',
        'callback' => '_salesforce_webform__ajax_load_upsert',
        'wrapper' => 'dropdown-second-replace',
      ),
		);
		$form['salesforce_webform_settings']['salesforce_object_upsert'] = array(
			'#type' => 'select',
			'#title' => t('Upsert this object on'),
			'#prefix' => '<div id="dropdown-second-replace">',
      '#suffix' => '</div>',
			'#options' => _salesforce_webform_load_object_fields($selected),
			'#description' => t('Select which field the object has to be upserted on (unique key).'),
			'#default_value' => (isset($form['#node']->salesforce_object_upsert)) ? $form['#node']->salesforce_object_upsert : 'Email'
		);
		
		// Subscribe to Salesforce Campaign
		$form['salesforce_webform_settings']['salesforce_campaign'] = array(
			'#type' => 'select',
			'#title' => t('Subscribe to Campaign'),
			'#options' => $campaigns,
			'#description' => t('Select which Campaign to subscribe to.'),
			'#default_value' => (isset($form['#node']->salesforce_campaign)) ? $form['#node']->salesforce_campaign : ''
		);
		// TODO: handle resend
		
		// Status that the Campaign needs to be put in for this Object
		$form['salesforce_webform_settings']['salesforce_campaign_status'] = array(
			'#type' => 'select',
			'#title' => t('Set Campaign status'),
			'#options' => $statuses,
			'#description' => t('Select the status to set the Campaign to.'),
			'#default_value' => (isset($form['#node']->salesforce_campaign_status)) ? $form['#node']->salesforce_campaign_status : ''
		);
	}
} // end function salesforce_webform_form_alter

/**
 * Selects just the second dropdown to be returned for re-rendering
 *
 * Since the controlling logic for populating the form is in the form builder
 * function, all we do here is select the element and return it to be updated.
 *
 * @return renderable array (the second dropdown)
 */
function _salesforce_webform__ajax_load_upsert($form, $form_state) {
  return $form['salesforce_webform_settings']['salesforce_object_upsert'];
}

function _salesforce_webform_load_object_fields ($selected) {
  foreach (salesforce_api_describeSObject($selected)->fields as $field)
	{
		$options[$field->name] = $field->label;
	}
  return $options;
}

/**
 * Implementation of MODULE_form_FORM_ID_alter
 * 
 * If Salesforce was enabled for the module, then add the Saleforces form elements
 * to the component edit form so that mapping to the salesforce object field can be done.
 */
function salesforce_webform_form_webform_component_edit_form_alter(&$form, &$form_state)
{
	$node = node_load($form['nid']['#value']);

	if ($node->use_salesforce == 1)
	{
		$form['salesforce_webform'] = array(
			'#type' => 'fieldset',
			'#title' => 'Salesforce',
			'#collapsible' => true,
			'#collapsed' => false
		);

		$options = array();
		$options['none'] = '--None--';
		// Should load from the selection in salesforce_webform_form_alter
		foreach (salesforce_api_describeSObject($node->salesforce_object)->fields as $field)
		{
			$options[$field->name] = $field->label;
		}

		$result = db_select('salesforce_webform_fieldmaps', 'swf')
					->fields('swf', array('sffname'))
					->condition('nid', $form['nid']['#value'])
					->condition('cid', $form['cid']['#value'])
					->execute()
					->fetchObject();

		$form['salesforce_webform']['object'] = array(
			'#type' => 'select',
			'#title' => 'Salesforce Object Field',
			'#options' => $options,
			'#default_value' => isset($result->sffname) ? $result->sffname : ''
		);
	}
} // end function salesforce_webform_form_webform_component_edit_form_alter


/**
 * Implementation of hook_webform_component_insert
 * 
 * Upon component insert (save) for the webform create the necessary field
 * mapping entry for webform component to Salesforce object field
 */
function salesforce_webform_webform_component_insert($component)
{
	if (!isset($component['salesforce_webform']))
		return;
  
  $component['mandatory'] = 1;

	db_insert('salesforce_webform_fieldmaps')
		->fields(array(
			'nid' => $component['nid'],
			'cid' => $component['cid'],
			'sffname' => $component['salesforce_webform']['object'],
		))
		->execute();
} // end function salesforce_webform_webform_component_insert

/**
 * Implementation hook_webform_component_update
 * 
 * Upon component update either insert/update field mapping entry for
 * webform component to Salesforce object field
 */
function salesforce_webform_webform_component_update($component)
{
	if (!isset($component['salesforce_webform']))
		return;

	if ($component['salesforce_webform']['object'] == 'none')
	{
		db_delete('salesforce_webform_fieldmaps')
			->condition('nid', $component['nid'])
			->condition('cid', $component['cid'])
			->execute();
	}
	else
	{
		$result = db_select('salesforce_webform_fieldmaps', 'swf')
					->fields('swf', array('sffname'))
					->condition('nid', $component['nid'])
					->condition('cid', $component['cid'])
					->execute()
					->fetchObject();

		if ($result)
		{
			db_update('salesforce_webform_fieldmaps')
				->fields(array(
					'sffname' => $component['salesforce_webform']['object'],
				))
				->condition('nid', $component['nid'])
				->condition('cid', $component['cid'])
				->execute();
		}
		else
		{
			db_insert('salesforce_webform_fieldmaps')
				->fields(array(
					'nid' => $component['nid'],
					'cid' => $component['cid'],
					'sffname' => $component['salesforce_webform']['object'],
				))
				->execute();
		}
		
	}

} // end function salesforce_webform_webform_component_update


/**
 * Implementation of hook_webform_component_delete
 * 
 * Delete any fieldmaps of the component to the salesforce object field
 */
function salesforce_webform_webform_component_delete($component)
{
	if (!isset($component['salesforce_webform']))
		return;

	db_delete('salesforce_webform_fieldmaps')
		->condition('nid', $component['nid'])
		->condition('cid', $component['cid'])
		->execute();
} // end function salesforce_webform_webform_component_delete


/**
 * Implementation of hook_webform_submission_insert
 * 
 * Upsert data into Salesforce via the Salesforce API
 */
function salesforce_webform_webform_submission_insert($node, $submission)
{
	if (!isset($node->use_salesforce) || (isset($node->use_salesforce) && $node->use_salesforce == 0))
		return;

  // TODO: add logging (which form) to salesforce when submitting
	$components = $node->webform['components'];

  $upsertvalue = $node->salesforce_object_upsert;
	$records = array();
	$record = array();
	foreach ($components as $key => $component)
	{
		$result = db_select('salesforce_webform_fieldmaps', 'swf')
					->fields('swf', array('sffname'))
					->condition('nid', $component['nid'])
					->condition('cid', $component['cid'])
					->execute()
					->fetchObject();

		if (!empty($result)) {
		  $record[$result->sffname] = $submission->data[$component['cid']]['value'][0];
		}
			
	}
	$records[] = $record;
	
	watchdog('salesforce_webform', "Upserting on $upsertvalue");

	// Upsert it into SalesForce
	$result = salesforce_api_upsert($records, $node->salesforce_object, $upsertvalue);
	
	if (isset($result['successes'][0]))
	{
		if (isset($result['created'][0]))
		{
			$sfid = $result['created'][0];
		}
		else if (isset($result['updated'][0]))
		{
			$sfid = $result['updated'][0];
		}
		
		// subscribe to Campaign
		if (isset($node->salesforce_campaign) && $node->salesforce_campaign != 0 && $node->salesforce_campaign != "none") {
		  $records[0] = new stdclass();
      $records[0]->CampaignId = $node->salesforce_campaign;
      $records[0]->ContactId = $sfid;
      if ($node->salesforce_campaign_status != "auto") $records[0]->Status = $node->salesforce_campaign_status;
      
		  salesforce_api_upsert($records,"CampaignMember");		  
		}


		db_insert('salesforce_webform_submissions')
			->fields(array(
				'sid' => $submission->sid,
				'sfid' => $sfid,
				'status' => 1
			))
			->execute();
	}
	else
	{
		db_insert('salesforce_webform_submissions')
			->fields(array(
				'sid' => $submission->sid,
				'status' => 2
			))
			->execute();
		
		watchdog('salesforce_webform', 'Salesforce Upsert failed');
	}
} // end function salesforce_webform_submission_insert


function salesforce_webform_resend_salesforce($nid, $sid)
{
	module_load_include('inc', 'webform', 'includes/webform.submissions');

  // TODO: add logging (which form) to salesforce when submitting

	$node = node_load($nid);
	$submission = webform_get_submission($nid, $sid);

	$components = db_select('webform_component', 'wc')
					->fields('wc')
					->condition('nid', $nid)
					->execute()
					->fetchAll();

	$records = array();
	$record = array();
	foreach ($components as $key => $component)
	{
		$result = db_select('salesforce_webform_fieldmaps', 'swf')
					->fields('swf', array('sffname'))
					->condition('nid', $component->nid)
					->condition('cid', $component->cid)
					->execute()
					->fetchObject();

		if (!empty($result))
			$record[$result->sffname] = $submission->data[$component->cid]['value'][0];
	}
	$records[] = $record;
	
  $upsertvalue = $node->salesforce_object_upsert;
	watchdog('salesforce_webform', "Upserting on $upsertvalue");

	// Upsert it into SalesForce
	$result = salesforce_api_upsert($records, $type = $node->salesforce_object, $upsertvalue);

	if (isset($result['successes'][0]))
	{
		if (isset($result['created'][0]))
		{
			$sfid = $result['created'][0];
		}
		else if (isset($result['updated'][0]))
		{
			$sfid = $result['updated'][0];
		}

		db_update('salesforce_webform_submissions')
			->fields(array(
				'sfid' => $sfid,
				'status' => 1
			))
			->condition('sid', $submission->sid)
			->execute();
			
    // subscribe to Campaign
		if (isset($node->salesforce_campaign) && $node->salesforce_campaign != 0 && $node->salesforce_campaign != "none") {
		  $records[0] = new stdclass();
      $records[0]->CampaignId = $node->salesforce_campaign;
      $records[0]->ContactId = $sfid;
      if ($node->salesforce_campaign_status != "auto") $records[0]->Status = $node->salesforce_campaign_status;
      
		  salesforce_api_upsert($records,"CampaignMember");		  
		}
			
		drupal_set_message('Resend to Salesforce Succeeded');
	}
	else
	{
		db_update('salesforce_webform_submissions')
			->fields(array(
				'status' => 2
			))
			->condition('sid', $submission->sid)
			->execute();
			
		drupal_set_message('Resend to Salesforce Failed', 'error');
	}

	if (isset($_REQUEST['destination']))
	{
		drupal_goto($_REQUEST['destination']);
	}
	else
	{
		drupal_goto("node/{$nid}/submission/{$sid}");
	}

} // end function salesforce_webform_resend_salesforce


